service: wompi-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  stage: dev
  environment:
      API_URL_SUPABASE: ${{ secrets.API_URL_SUPABASE }} 
      ANON_API_KEY: ${{ secrets.ANON_API_KEY }}    
  httpApi:
    cors: true

plugins:
  - serverless-offline

package:
  individually: true
  include:
    - dist/**
  exclude:
    - node_modules/**
    - test/**
    - coverage/**

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi: '*'