service: wompi-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  stage: dev
  environment:
      API_URL_SUPABASE: ${secrets:API_URL_SUPABASE}
      ANON_API_KEY: ${secrets:ANON_API_KEY}    
  httpApi:
    cors: true

plugins:
  - serverless-offline

package:
  individually: false
  patterns:
    - '!node_modules/**/@nestjs/**/schematics/**'
    - '!node_modules/**/test/**'
    - '!node_modules/**/tests/**'
    - '!node_modules/**/*.md'
    - '!**/*.map'

functions:
  api:
    handler: dist/lambda.lambdaHandler
    events:
      - httpApi: '*'
    environment:
      NODE_OPTIONS: '--enable-source-maps'